[2024-04-20T16:13:28.386+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T16:13:26.460064+00:00 [queued]>
[2024-04-20T16:13:28.399+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T16:13:26.460064+00:00 [queued]>
[2024-04-20T16:13:28.400+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-20T16:13:28.419+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-04-20 16:13:26.460064+00:00
[2024-04-20T16:13:28.430+0000] {standard_task_runner.py:57} INFO - Started process 70 to run task
[2024-04-20T16:13:28.431+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-04-20T16:13:26.460064+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp5nz1nyix']
[2024-04-20T16:13:28.435+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask reddit_extraction
[2024-04-20T16:13:28.492+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T16:13:26.460064+00:00 [running]> on host a5ce8015e481
[2024-04-20T16:13:28.614+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tawfik Yasser' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T16:13:26.460064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T16:13:26.460064+00:00'
[2024-04-20T16:13:29.415+0000] {logging_mixin.py:151} INFO - Number of posts = 10
[2024-04-20T16:13:29.416+0000] {logging_mixin.py:151} INFO - 0     object
1      int64
2     object
3     object
4      int64
5    float64
6     object
7     object
dtype: object
[2024-04-20T16:13:29.417+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 27, in reddit_pipeline
    transformed_data = transform_posts(posts_df)
  File "/opt/airflow/etls/reddit_etl.py", line 13, in transform_posts
    post_df = post_df.drop('created', axis=1)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 5347, in drop
    return super().drop(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6992, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['created'] not found in axis"
[2024-04-20T16:13:29.430+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20240420T161326, start_date=20240420T161328, end_date=20240420T161329
[2024-04-20T16:13:29.446+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task reddit_extraction ("['created'] not found in axis"; 70)
[2024-04-20T16:13:29.495+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-20T16:13:29.512+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
